[workspace]
members = [
    "acceptance",
    "derive-macros",
    "ffi",
    "kernel",
    "kernel/examples/*",
    "test-utils",
    "feature-tests",
]
# Only check / build main crates by default (check all with `--workspace`)
default-members = ["acceptance", "kernel"]
resolver = "2"

[workspace.package]
edition = "2021"
homepage = "https://delta.io"
keywords = ["deltalake", "delta", "datalake"]
license = "Apache-2.0"
repository = "https://github.com/delta-io/delta-kernel-rs"
readme = "README.md"
rust-version = "1.80"
version = "0.6.1"

[workspace.dependencies]
# When changing the arrow version range, also modify ffi/Cargo.toml which has
# its own arrow version ranges witeh modified features. Failure to do so will
# result in compilation errors as two different sets of arrow dependencies may
# be sourced
arrow = { version = "54.2.1" }
arrow-arith = { version = "54.2.1" }
arrow-array = { version = "54.2.1" }
arrow-buffer = { version = "54.2.1" }
arrow-cast = { version = "54.2.1" }
arrow-data = { version = "54.2.1" }
arrow-ord = { version = "54.2.1" }
arrow-json = { version = "54.2.1" }
arrow-select = { version = "54.2.1" }
arrow-schema = { version = "54.2.1" }
parquet = { version = "54.2.1", features = ["object_store"] }
object_store = { version = ">=0.11, <0.12" }
hdfs-native-object-store = "0.12.0"
hdfs-native = "0.10.0"
walkdir = "2.5.0"
